### PR TITLE
Add parallel to cc7 build

### PR DESCRIPTION
**Pull request by fcatalan92**
The package parallel is currently used in the O2 HF developments. It would be nice to have it already installed.

### CODE REVIEW

**Review by mconcas — APPROVED** [review]
Ready for next release

**Comment by vkucera** [comment]
@mconcas Any reason why this has not been merged yet?

**Comment by fcatalan92** [comment]
> @mconcas Any reason why this has not been merged yet?

The idea was to wait for the next release to not force a container update to everyone only for this feature

**Comment by vkucera** [comment]
> > @mconcas Any reason why this has not been merged yet?
> 
> The idea was to wait for the next release to not force a container update to everyone only for this feature

OK, thanks.

**Comment by mconcas** [comment]
> @mconcas Any reason why this has not been merged yet?

Alidock main container is not supposed to host something that is not strictly required for compilation and runtime of the application itself.

In principle to add custom requirements for specific use cases is not supported.
I'll do an exception for this specific case for the `parallel` executable as it is quite harmless and reasonably standard GNU program.

I encourage, for other similar cases, to create a custom container that is based on latest alidock image and add further customisation there (see, e.g. `alipier/alicuda`).
Then it can be also hosted here on the alipier repository and benefit of automatic builds in case of upgrades.

Regards,
Matteo

**Pull request merged**
